# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'DBWeibo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DBWeibo

  pod 'AFNetworking'
  pod 'SDWebImage'
  pod 'SnapKit'
  pod 'SVProgressHUD'
  pod 'MJRefresh'

end
